configfile: "configs/config.yaml"

CONFIG_FILE = "configs/config.yaml"
ENV_FILE = "envs/ml_rna_mod.yml"
RAW_DIR = config["paths"]["raw_dir"]
INTERIM_DIR = config["paths"]["interim_dir"]
PROCESSED_DIR = config["paths"]["processed_dir"]

DOWNLOAD_MARKER = f"{RAW_DIR}/.sources_downloaded.ok"

UNIPROT_RECORDS = f"{INTERIM_DIR}/uniprot/uniprot_records.parquet"
RHEA_REACTIONS = f"{INTERIM_DIR}/rhea/rhea_reactions.parquet"
GO_TERMS = f"{INTERIM_DIR}/go/go_terms.parquet"
MODOMICS_RECORDS = f"{INTERIM_DIR}/modomics/modomics_records.parquet"
ECOCYC_RECORDS = f"{INTERIM_DIR}/ecocyc/ecocyc_records.parquet"
MANUAL_LITERATURE_RECORDS = f"{INTERIM_DIR}/manual_literature/manual_literature_records.parquet"
LEGACY_PILOT_RECORDS = f"{INTERIM_DIR}/legacy_pilot/legacy_pilot_records.parquet"

MASTER = f"{PROCESSED_DIR}/rnmod_master.parquet"
MASTER_TSV = f"{PROCESSED_DIR}/rnmod_master.tsv.gz"
SEQUENCES = f"{PROCESSED_DIR}/rnmod_sequences.faa"
LABEL_MATRIX = f"{PROCESSED_DIR}/rnmod_label_matrix.parquet"
SOURCE_MANIFEST = f"{PROCESSED_DIR}/source_manifest.tsv"
DATASET_CARD = f"{PROCESSED_DIR}/rnmod_dataset_card.md"


rule all:
    input:
        MASTER,
        MASTER_TSV,
        SEQUENCES,
        LABEL_MATRIX,
        SOURCE_MANIFEST,
        DATASET_CARD


rule download_sources:
    input:
        config_file=CONFIG_FILE,
        uniprot_query=config["sources"]["uniprot"]["query_config"]
    output:
        DOWNLOAD_MARKER
    conda:
        ENV_FILE
    shell:
        "PYTHONPATH=src python scripts/00_data_download/00_download_sources.py --config {input.config_file} --marker {output}"


rule ingest_uniprot:
    input:
        DOWNLOAD_MARKER
    output:
        UNIPROT_RECORDS
    conda:
        ENV_FILE
    shell:
        "PYTHONPATH=src python -m rnmod.cli ingest-uniprot --config {CONFIG_FILE} --output {output}"


rule ingest_rhea:
    input:
        DOWNLOAD_MARKER
    output:
        RHEA_REACTIONS
    conda:
        ENV_FILE
    shell:
        "PYTHONPATH=src python -m rnmod.cli ingest-rhea --config {CONFIG_FILE} --output {output}"


rule ingest_go:
    input:
        DOWNLOAD_MARKER
    output:
        GO_TERMS
    conda:
        ENV_FILE
    shell:
        "PYTHONPATH=src python -m rnmod.cli ingest-go --config {CONFIG_FILE} --output {output}"


rule ingest_modomics:
    input:
        DOWNLOAD_MARKER,
        config["sources"]["modomics"]["manual_table"]
    output:
        MODOMICS_RECORDS
    conda:
        ENV_FILE
    shell:
        "PYTHONPATH=src python -m rnmod.cli ingest-modomics --config {CONFIG_FILE} --output {output}"


rule ingest_ecocyc:
    input:
        DOWNLOAD_MARKER,
        config["sources"]["ecocyc"]["manual_table"]
    output:
        ECOCYC_RECORDS
    conda:
        ENV_FILE
    shell:
        "PYTHONPATH=src python -m rnmod.cli ingest-ecocyc --config {CONFIG_FILE} --output {output}"


rule ingest_manual_literature:
    input:
        DOWNLOAD_MARKER,
        config["sources"]["manual_literature"]["table"]
    output:
        MANUAL_LITERATURE_RECORDS
    conda:
        ENV_FILE
    shell:
        "PYTHONPATH=src python -m rnmod.cli ingest-manual-literature --config {CONFIG_FILE} --output {output}"


rule ingest_legacy_pilot:
    input:
        DOWNLOAD_MARKER
    output:
        LEGACY_PILOT_RECORDS
    conda:
        ENV_FILE
    shell:
        "PYTHONPATH=src python -m rnmod.cli ingest-legacy-pilot --config {CONFIG_FILE} --output {output}"


rule build_master:
    input:
        uniprot=UNIPROT_RECORDS,
        rhea=RHEA_REACTIONS,
        go=GO_TERMS,
        modomics=MODOMICS_RECORDS,
        ecocyc=ECOCYC_RECORDS,
        manual=MANUAL_LITERATURE_RECORDS,
        legacy=LEGACY_PILOT_RECORDS
    output:
        master=MASTER,
        master_tsv=MASTER_TSV,
        fasta=SEQUENCES,
        labels=LABEL_MATRIX,
        manifest=SOURCE_MANIFEST,
        card=DATASET_CARD
    conda:
        ENV_FILE
    shell:
        "PYTHONPATH=src python -m rnmod.cli build-master --config {CONFIG_FILE}"
