name: ML_RNA_mod
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11
  - biopython
  - duckdb
  - numpy
  - pandas
  - polars
  - pyarrow
  - pydantic
  - pyyaml
  - requests
  - scikit-learn
  - typer
  - pytest
  - snakemake-minimal
  - mmseqs2
  - hmmer
  - mafft
  - pip
